//
// SM70 QPN8 FP8 dense GEMM regression.
//
// Validates the torch-free QPN8 bridge (src/devices/cuda/sm70/qpn8_fp8.cu)
// against an independent CPU FP32 oracle. Requires a single SM70 (V100) GPU;
// exits 77 when the required GPU or compiled kernels are unavailable so ctest
// skips it elsewhere.
//
// The oracle decodes FP8_E4M3 weights in FP32 and applies the same 256x scale
// convention QPN8 uses internally, so it checks the GEMM accumulation and the
// packed weight/scale layout without depending on QPN8's own dequant kernel.
//

#include "devices/cuda/fastllm-sm70.cuh"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include <cuda_fp16.h>
#include <cuda_runtime.h>

namespace {

constexpr int kPass = 0;
constexpr int kFail = 1;
constexpr int kSkip = 77;

int GpuMajor = 0;
int GpuMinor = 0;

bool CheckCuda(cudaError_t err, const char* what) {
  if (err != cudaSuccess) {
    std::fprintf(stderr, "CUDA error in %s: %s\n", what,
                 cudaGetErrorString(err));
    return false;
  }
  return true;
}

// Independent FP8_E4M3FN -> float decode, built from raw IEEE bits so it does
// not share any code path with the kernel's half conversion. 0x7F/0xFF (NaN)
// are never generated by the test, so they are not handled here.
float Fp8E4M3ToFloat(uint8_t x) {
  const unsigned sign = (x >> 7) & 1u;
  const unsigned exp = (x >> 3) & 0x0fu;
  const unsigned mant = x & 0x07u;
  if (exp == 0) {
    // Subnormal: mant * 2^-9, exactly representable in float.
    const float v = static_cast<float>(mant) * 0.001953125f;
    return sign ? -v : v;
  }
  // Normal: (1 + mant/8) * 2^(exp-7). The IEEE fields line up directly once
  // float's bias 127 replaces fp8's bias 7 (exp + 120).
  const unsigned bits = (sign << 31) | ((exp + 120u) << 23) | (mant << 20);
  return *reinterpret_cast<const float*>(&bits);
}

// Deterministic PRNG (xorshift32) so the test is reproducible.
struct Rng {
  uint32_t state;
  explicit Rng(uint32_t seed) : state(seed ? seed : 0x1234567u) {}
  uint32_t Next() {
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
  }
  // Random FP8 code in [0, 126], skipping the two NaN encodings.
  uint8_t Fp8Code() {
    uint8_t v;
    do {
      v = static_cast<uint8_t>(Next() & 0xffu);
    } while (v == 0x7f || v == 0xff);
    return v;
  }
  float SmallPositive() {
    // Scale in [0.001, 0.5]; *256 stays well within half range.
    return 0.001f + static_cast<float>(Next() % 500u) * 0.001f;
  }
  half HalfInUnit() {
    // half in [-1, 1].
    const float v = (static_cast<float>(Next() % 2001u) - 1000.0f) / 1000.0f;
    return __float2half(v);
  }
};

struct Case {
  int m, k, n;
  bool channelScales;
  const char* name;
};

// Runs one (m, k, n, scale-layout) case and returns true when the QPN8 output
// matches the FP32 oracle within the relative-L2 tolerance.
bool RunCase(const Case& c, float relTol) {
  Rng rng(static_cast<uint32_t>(c.m * 100000 + c.k * 1000 + c.n));

  std::vector<uint8_t> weight(static_cast<size_t>(c.n) * c.k);
  for (auto& b : weight) {
    b = rng.Fp8Code();
  }

  std::vector<float> scales;
  if (c.channelScales) {
    scales.resize(c.n);
    for (auto& s : scales) {
      s = rng.SmallPositive();
    }
  } else {
    scales.resize(static_cast<size_t>(c.n / 128) * (c.k / 128));
    for (auto& s : scales) {
      s = rng.SmallPositive();
    }
  }

  std::vector<half> input(static_cast<size_t>(c.m) * c.k);
  for (auto& h : input) {
    h = rng.HalfInUnit();
  }

  const size_t codesBytes = static_cast<size_t>(c.k) * c.n;
  const size_t scaleHalves = c.channelScales
                                 ? static_cast<size_t>(c.n)
                                 : static_cast<size_t>(c.k / 128) * (c.n / 32);

  uint8_t* dCodes = nullptr;
  half* dScales = nullptr;
  half* dIn = nullptr;
  half* dOut = nullptr;
  uint8_t* dWeight = nullptr;
  float* dScalesIn = nullptr;
  if (!CheckCuda(cudaMalloc(&dCodes, codesBytes), "malloc codes") ||
      !CheckCuda(cudaMalloc(&dScales, scaleHalves * sizeof(half)),
                 "malloc scales") ||
      !CheckCuda(cudaMalloc(&dIn, input.size() * sizeof(half)), "malloc in") ||
      !CheckCuda(cudaMalloc(&dOut, static_cast<size_t>(c.m) * c.n * sizeof(half)),
                 "malloc out") ||
      !CheckCuda(cudaMalloc(&dWeight, weight.size()), "malloc weight") ||
      !CheckCuda(cudaMalloc(&dScalesIn, scales.size() * sizeof(float)),
                 "malloc weight scales")) {
    return false;
  }
  CheckCuda(cudaMemcpy(dIn, input.data(), input.size() * sizeof(half),
                       cudaMemcpyHostToDevice),
            "copy in");
  CheckCuda(cudaMemcpy(dWeight, weight.data(), weight.size(),
                       cudaMemcpyHostToDevice),
            "copy weight");
  CheckCuda(cudaMemcpy(dScalesIn, scales.data(), scales.size() * sizeof(float),
                       cudaMemcpyHostToDevice),
            "copy weight scales");

  const bool prepared =
      fastllm::sm70::Fp8QpnPrepare(dWeight, dScalesIn, dCodes,
                                   dScales, c.k, c.n, c.channelScales,
                                   cudaStreamPerThread);
  const auto release = [&]() {
    cudaFree(dCodes);
    cudaFree(dScales);
    cudaFree(dIn);
    cudaFree(dOut);
    cudaFree(dWeight);
    cudaFree(dScalesIn);
  };

  if (!prepared) {
    std::fprintf(stderr, "  [%s] prepare failed\n", c.name);
    release();
    return false;
  }

  const bool ran = fastllm::sm70::Fp8QpnGemm(dCodes, dScales, dIn, dOut, c.m,
                                             c.k, c.n, c.channelScales,
                                             cudaStreamPerThread);
  if (!ran) {
    std::fprintf(stderr, "  [%s] gemm refused (m=%d k=%d n=%d ch=%d)\n",
                 c.name, c.m, c.k, c.n, (int)c.channelScales);
    release();
    return false;
  }
  CheckCuda(cudaStreamSynchronize(cudaStreamPerThread), "sync");

  std::vector<half> out(static_cast<size_t>(c.m) * c.n);
  CheckCuda(cudaMemcpy(out.data(), dOut, out.size() * sizeof(half),
                       cudaMemcpyDeviceToHost),
            "copy out");

  // Independent FP32 oracle: standard dequantized GEMM with the physical FP8
  // value and its block/channel scale. The QPN8 256x scale convention cancels
  // internally (the fp8 decoder yields value/256, prepare multiplies by 256),
  // so the externally visible result is the plain dequantized product.
  double num = 0.0, den = 0.0;
  for (int m = 0; m < c.m; ++m) {
    for (int n = 0; n < c.n; ++n) {
      float acc = 0.0f;
      for (int k = 0; k < c.k; ++k) {
        const float w = Fp8E4M3ToFloat(weight[static_cast<size_t>(n) * c.k + k]);
        const float s = c.channelScales
                            ? scales[n]
                            : scales[static_cast<size_t>(n / 128) * (c.k / 128) +
                                     (k / 128)];
        acc += __half2float(input[static_cast<size_t>(m) * c.k + k]) * w * s;
      }
      const float got = __half2float(out[static_cast<size_t>(m) * c.n + n]);
      num += static_cast<double>(got - acc) * (got - acc);
      den += static_cast<double>(acc) * acc;
    }
  }
  const float rel = den > 0.0 ? static_cast<float>(std::sqrt(num / den)) : 0.0f;
  std::printf("  [%s] m=%d k=%d n=%d ch=%d relL2=%.3e %s\n", c.name, c.m, c.k,
              c.n, (int)c.channelScales, rel, rel <= relTol ? "OK" : "FAIL");

  if (std::getenv("SM70_QPN_DEBUG") != nullptr) {
    for (int idx = 0; idx < std::min(4, c.n); ++idx) {
      float acc = 0.0f;
      for (int k = 0; k < c.k; ++k) {
        const float w = Fp8E4M3ToFloat(weight[static_cast<size_t>(idx) * c.k + k]);
        const float s = c.channelScales
                            ? scales[idx]
                            : scales[static_cast<size_t>(idx / 128) * (c.k / 128) +
                                     (k / 128)];
        acc += __half2float(input[k]) * w * s;
      }
      std::printf("    col=%d got=%.6f oracle=%.6f\n", idx,
                  __half2float(out[idx]), acc);
    }
  }

  release();
  return rel <= relTol;
}

}  // namespace

int main(int argc, char** argv) {
  int dev = 0;
  if (cudaGetDevice(&dev) != cudaSuccess) {
    std::printf("SKIP: no CUDA device\n");
    return kSkip;
  }
  if (cudaDeviceGetAttribute(&GpuMajor, cudaDevAttrComputeCapabilityMajor, dev) !=
          cudaSuccess ||
      cudaDeviceGetAttribute(&GpuMinor, cudaDevAttrComputeCapabilityMinor, dev) !=
          cudaSuccess) {
    std::printf("SKIP: cannot query compute capability\n");
    return kSkip;
  }
  if (GpuMajor != 7 || GpuMinor != 0) {
    std::printf("SKIP: requires SM70 (got sm_%d%d)\n", GpuMajor, GpuMinor);
    return kSkip;
  }

  // Rollback switch: FASTLLM_SM70_FP8_QPN8=0 must disable the path.
  setenv("FASTLLM_SM70_FP8_QPN8", "0", 1);
  if (fastllm::sm70::Fp8QpnSupported()) {
    std::fprintf(stderr, "FAIL: Fp8QpnSupported should be false with "
                         "FASTLLM_SM70_FP8_QPN8=0\n");
    return kFail;
  }
  unsetenv("FASTLLM_SM70_FP8_QPN8");
  if (!fastllm::sm70::Fp8QpnSupported()) {
    std::printf("SKIP: QPN8 kernels not compiled for this device\n");
    return kSkip;
  }

  const Case cases[] = {
      // block-128 scales (FastLLM native), m <= 8
      {1, 256, 256, false, "block_m1"},
      {4, 256, 256, false, "block_m4"},
      {8, 128, 256, false, "block_m8"},
      // channel scales, m > 8
      {16, 256, 256, true, "chan_m16"},
      {32, 256, 256, true, "chan_m32"},
      {16, 64, 256, true, "chan_m16_k64"},
      // Representative Qwen3.8-Flash-Next dense projection shapes.
      {4, 2560, 2560, false, "block_m4_hidden"},
      {16, 5120, 2560, true, "chan_m16_down"},
  };

  bool allOk = true;
  for (const Case& c : cases) {
    allOk = RunCase(c, 2e-3f) && allOk;
  }

  if (!allOk) {
    std::fprintf(stderr, "FAIL: one or more QPN8 cases diverged\n");
    return kFail;
  }
  std::printf("PASS: sm70 QPN8 FP8 regression\n");
  return kPass;
}
