//
// SM70 QPN2 NVFP4 dense GEMM regression.
//
// Validates the torch-free QPN2 bridge (src/devices/cuda/sm70/qpn2_nvfp4.cu)
// against an independent CPU FP32 oracle. Requires a single SM70 (V100) GPU;
// exits 77 when the required GPU or compiled kernels are unavailable so ctest
// skips it elsewhere.
//
// The oracle decodes NVFP4 E2M1 weights and FP8_E4M3 group scales in FP32, so
// it checks GEMM accumulation and the packed layout without depending on
// QPN2's own dequant kernel.
//

#include "devices/cuda/fastllm-sm70.cuh"

#include <algorithm>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>

#include <cuda_fp16.h>
#include <cuda_runtime.h>

namespace {

constexpr int kPass = 0;
constexpr int kFail = 1;
constexpr int kSkip = 77;

int GpuMajor = 0;
int GpuMinor = 0;

bool CheckCuda(cudaError_t err, const char* what) {
  if (err != cudaSuccess) {
    std::fprintf(stderr, "CUDA error in %s: %s\n", what,
                 cudaGetErrorString(err));
    return false;
  }
  return true;
}

// Independent NVFP4 E2M1 -> float decode from the 4-bit nibble.
float E2M1ToFloat(uint8_t nibble) {
  const bool sign = (nibble & 0x8u) != 0;
  const int exp = (nibble >> 1) & 0x3;
  const int mant = nibble & 0x1;
  float v = 0.0f;
  if (exp == 0) {
    v = mant ? 0.5f : 0.0f;
  } else {
    v = (1.0f + 0.5f * static_cast<float>(mant)) *
        static_cast<float>(1 << (exp - 1));
  }
  return sign ? -v : v;
}

// Independent FP8_E4M3FN -> float decode, same construction as the QPN8
// oracle. 0x7F/0xFF (NaN) are never generated by the test.
float Fp8E4M3ToFloat(uint8_t x) {
  const unsigned sign = (x >> 7) & 1u;
  const unsigned exp = (x >> 3) & 0x0fu;
  const unsigned mant = x & 0x07u;
  if (exp == 0) {
    const float v = static_cast<float>(mant) * 0.001953125f;
    return sign ? -v : v;
  }
  const unsigned bits = (sign << 31) | ((exp + 120u) << 23) | (mant << 20);
  return *reinterpret_cast<const float*>(&bits);
}

struct Rng {
  uint32_t state;
  explicit Rng(uint32_t seed) : state(seed ? seed : 0x1234567u) {}
  uint32_t Next() {
    state ^= state << 13;
    state ^= state >> 17;
    state ^= state << 5;
    return state;
  }
  uint8_t Nibble() { return static_cast<uint8_t>(Next() & 0x0fu); }
  // Small positive FP8_E4M3 in ~[0.0156, 0.5] so k=1536 GEMM stays inside
  // half range. Random full-range FP8 scales overflow half and make relL2 NaN.
  uint8_t Fp8SmallPositive() {
    const unsigned exp = 1u + (Next() % 6u);
    const unsigned mant = Next() % 8u;
    return static_cast<uint8_t>((exp << 3) | mant);
  }
  half HalfInUnit() {
    const float v = (static_cast<float>(Next() % 2001u) - 1000.0f) / 1000.0f;
    return __float2half(v);
  }
};

struct Case {
  int m, k, n;
  float globalScale;
  const char* name;
};

bool RunCase(const Case& c, float relTol) {
  Rng rng(static_cast<uint32_t>(c.m * 100000 + c.k * 1000 + c.n));

  std::vector<uint8_t> weight(static_cast<size_t>(c.n) * (c.k / 2));
  for (size_t i = 0; i < weight.size(); ++i) {
    const uint8_t lo = rng.Nibble();
    const uint8_t hi = rng.Nibble();
    weight[i] = static_cast<uint8_t>(lo | (hi << 4));
  }

  std::vector<uint8_t> scales(static_cast<size_t>(c.n) * (c.k / 16));
  for (auto& s : scales) {
    s = rng.Fp8SmallPositive();
  }

  std::vector<half> input(static_cast<size_t>(c.m) * c.k);
  for (auto& h : input) {
    h = rng.HalfInUnit();
  }

  const size_t codesBytes = static_cast<size_t>(c.n) * c.k / 2;
  const size_t scaleBytes = static_cast<size_t>(c.n) * c.k / 16;

  uint8_t* dCodes = nullptr;
  uint8_t* dPackedScales = nullptr;
  half* dIn = nullptr;
  half* dOut = nullptr;
  uint8_t* dWeight = nullptr;
  uint8_t* dScalesIn = nullptr;
  if (!CheckCuda(cudaMalloc(&dCodes, codesBytes), "malloc codes") ||
      !CheckCuda(cudaMalloc(&dPackedScales, scaleBytes), "malloc packed scales") ||
      !CheckCuda(cudaMalloc(&dIn, input.size() * sizeof(half)), "malloc in") ||
      !CheckCuda(cudaMalloc(&dOut, static_cast<size_t>(c.m) * c.n * sizeof(half)),
                 "malloc out") ||
      !CheckCuda(cudaMalloc(&dWeight, weight.size()), "malloc weight") ||
      !CheckCuda(cudaMalloc(&dScalesIn, scales.size()), "malloc weight scales")) {
    return false;
  }
  CheckCuda(cudaMemcpy(dIn, input.data(), input.size() * sizeof(half),
                       cudaMemcpyHostToDevice),
            "copy in");
  CheckCuda(cudaMemcpy(dWeight, weight.data(), weight.size(),
                       cudaMemcpyHostToDevice),
            "copy weight");
  CheckCuda(cudaMemcpy(dScalesIn, scales.data(), scales.size(),
                       cudaMemcpyHostToDevice),
            "copy weight scales");

  const bool prepared = fastllm::sm70::Nvfp4QpnPrepare(
      dWeight, dScalesIn, dCodes, dPackedScales, c.k, c.n, cudaStreamPerThread);
  const auto release = [&]() {
    cudaFree(dCodes);
    cudaFree(dPackedScales);
    cudaFree(dIn);
    cudaFree(dOut);
    cudaFree(dWeight);
    cudaFree(dScalesIn);
  };

  if (!prepared) {
    std::fprintf(stderr, "  [%s] prepare failed\n", c.name);
    release();
    return false;
  }

  const bool ran = fastllm::sm70::Nvfp4QpnGemm(
      dCodes, dPackedScales, dIn, dOut, c.m, c.k, c.n, c.globalScale,
      cudaStreamPerThread);
  if (!ran) {
    std::fprintf(stderr, "  [%s] gemm refused (m=%d k=%d n=%d)\n", c.name, c.m,
                 c.k, c.n);
    release();
    return false;
  }
  CheckCuda(cudaStreamSynchronize(cudaStreamPerThread), "sync");

  std::vector<half> out(static_cast<size_t>(c.m) * c.n);
  CheckCuda(cudaMemcpy(out.data(), dOut, out.size() * sizeof(half),
                       cudaMemcpyDeviceToHost),
            "copy out");

  double num = 0.0, den = 0.0;
  for (int m = 0; m < c.m; ++m) {
    for (int n = 0; n < c.n; ++n) {
      float acc = 0.0f;
      for (int k = 0; k < c.k; ++k) {
        const uint8_t packed =
            weight[static_cast<size_t>(n) * (c.k / 2) + (k >> 1)];
        const uint8_t fp4 = (k & 1) ? (packed >> 4) : (packed & 0x0f);
        const uint8_t scaleCode =
            scales[static_cast<size_t>(n) * (c.k / 16) + (k / 16)];
        acc += __half2float(input[static_cast<size_t>(m) * c.k + k]) *
               E2M1ToFloat(fp4) * Fp8E4M3ToFloat(scaleCode) * c.globalScale;
      }
      const float got = __half2float(out[static_cast<size_t>(m) * c.n + n]);
      num += static_cast<double>(got - acc) * (got - acc);
      den += static_cast<double>(acc) * acc;
    }
  }
  const float rel = den > 0.0 ? static_cast<float>(std::sqrt(num / den)) : 0.0f;
  std::printf("  [%s] m=%d k=%d n=%d scale=%.3f relL2=%.3e %s\n", c.name, c.m,
              c.k, c.n, c.globalScale, rel, rel <= relTol ? "OK" : "FAIL");
  if (!(rel <= relTol)) {
    const float got0 = __half2float(out[0]);
    float acc0 = 0.0f;
    for (int k = 0; k < c.k; ++k) {
      const uint8_t packed = weight[k >> 1];
      const uint8_t fp4 = (k & 1) ? (packed >> 4) : (packed & 0x0f);
      acc0 += __half2float(input[k]) * E2M1ToFloat(fp4) *
              Fp8E4M3ToFloat(scales[k / 16]) * c.globalScale;
    }
    std::printf("    col0 got=%.6f oracle=%.6f\n", got0, acc0);
  }

  release();
  return rel <= relTol;
}

bool RunNativeCase(const Case& c, float relTol, bool outOfPlace = false) {
  Rng rng(static_cast<uint32_t>(c.m * 70000 + c.k * 300 + c.n + 17));
  const int groups = c.k / 16;
  const size_t rowBytes = static_cast<size_t>(groups) * 12;
  std::vector<uint8_t> native(static_cast<size_t>(c.n) * rowBytes, 0);
  std::vector<uint8_t> scales(static_cast<size_t>(c.n) * groups);
  std::vector<uint8_t> packed(static_cast<size_t>(c.n) * (c.k / 2));

  for (int col = 0; col < c.n; ++col) {
    for (int group = 0; group < groups; ++group) {
      const uint8_t scaleCode = rng.Fp8SmallPositive();
      scales[static_cast<size_t>(col) * groups + group] = scaleCode;
      uint8_t* block = native.data() + static_cast<size_t>(col) * rowBytes +
                       static_cast<size_t>(group) * 12;
      for (int offset = 0; offset < 16; offset += 2) {
        const uint8_t lo = rng.Nibble();
        const uint8_t hi = rng.Nibble();
        block[offset >> 1] = static_cast<uint8_t>(lo | (hi << 4));
        packed[static_cast<size_t>(col) * (c.k / 2) + (group * 8 + (offset >> 1))] =
            block[offset >> 1];
      }
      // Native layout stores fused FP32 = E4M3 * globalScale. Prepare unfuses
      // back to E4M3; GEMM then multiplies the same globalScale, matching 1Cat.
      const float fused = Fp8E4M3ToFloat(scaleCode) * c.globalScale;
      std::memcpy(block + 8, &fused, sizeof(float));
    }
  }

  std::vector<half> input(static_cast<size_t>(c.m) * c.k);
  for (auto& h : input) {
    h = rng.HalfInUnit();
  }

  uint8_t* dStorage = nullptr;
  uint8_t* dSidecar = nullptr;
  half* dIn = nullptr;
  half* dOut = nullptr;
  // The sidecar is padded up to the 32-column tile, so it can need more room
  // than the native source. The tail canary catches a partial tile writing
  // past the logical row width: an overflowing row corrupts the start of the
  // next one and shows up in the oracle, while the last row would land past
  // the buffer.
  const size_t packedBytes = fastllm::sm70::Nvfp4QpnPackedBytes(c.k, c.n);
  // `outOfPlace` mirrors the engine: storage exactly the native source size,
  // sidecar a separate Nvfp4QpnPackedBytes allocation. In place, storage has to
  // hold both.
  const size_t storageBytes =
      outOfPlace ? native.size() : std::max(native.size(), packedBytes);
  const size_t outElements = static_cast<size_t>(c.m) * c.n;
  constexpr int kCanary = 32;
  constexpr uint16_t kSentinel = 0x7e01;

  if (!CheckCuda(cudaMalloc(&dStorage, storageBytes), "malloc native") ||
      (outOfPlace &&
       !CheckCuda(cudaMalloc(&dSidecar, packedBytes), "malloc sidecar")) ||
      !CheckCuda(cudaMalloc(&dIn, input.size() * sizeof(half)), "malloc native in") ||
      !CheckCuda(cudaMalloc(&dOut, (outElements + kCanary) * sizeof(half)),
                 "malloc native out")) {
    return false;
  }
  {
    std::vector<half> seeded(outElements + kCanary,
                             __ushort_as_half(kSentinel));
    CheckCuda(cudaMemcpy(dOut, seeded.data(), seeded.size() * sizeof(half),
                         cudaMemcpyHostToDevice),
              "seed native canary");
  }
  CheckCuda(cudaMemcpy(dStorage, native.data(), native.size(),
                       cudaMemcpyHostToDevice),
            "copy native");
  CheckCuda(cudaMemcpy(dIn, input.data(), input.size() * sizeof(half),
                       cudaMemcpyHostToDevice),
            "copy native in");

  const auto release = [&]() {
    cudaFree(dStorage);
    if (dSidecar != nullptr) {
      cudaFree(dSidecar);
    }
    cudaFree(dIn);
    cudaFree(dOut);
  };

  if (!fastllm::sm70::Nvfp4QpnPrepareFromNative(
          dStorage, storageBytes, c.k, c.n, c.globalScale,
          cudaStreamPerThread, dSidecar, packedBytes)) {
    std::fprintf(stderr, "  [%s] native prepare failed\n", c.name);
    release();
    return false;
  }
  uint8_t* sidecar = dSidecar != nullptr ? dSidecar : dStorage;
  const bool ran = fastllm::sm70::Nvfp4QpnGemm(
      sidecar, sidecar + fastllm::sm70::Nvfp4QpnScaleOffset(c.k, c.n), dIn,
      dOut, c.m, c.k, c.n, c.globalScale, cudaStreamPerThread);
  if (!ran) {
    std::fprintf(stderr, "  [%s] native gemm refused\n", c.name);
    release();
    return false;
  }
  CheckCuda(cudaStreamSynchronize(cudaStreamPerThread), "native sync");

  std::vector<half> outFull(outElements + kCanary);
  CheckCuda(cudaMemcpy(outFull.data(), dOut, outFull.size() * sizeof(half),
                       cudaMemcpyDeviceToHost),
            "copy native out");
  int canaryHits = 0;
  for (int i = 0; i < kCanary; ++i) {
    if (__half_as_ushort(outFull[outElements + i]) != kSentinel) {
      ++canaryHits;
    }
  }

  double num = 0.0, den = 0.0;
  for (int m = 0; m < c.m; ++m) {
    for (int n = 0; n < c.n; ++n) {
      float acc = 0.0f;
      for (int k = 0; k < c.k; ++k) {
        const uint8_t packedByte =
            packed[static_cast<size_t>(n) * (c.k / 2) + (k >> 1)];
        const uint8_t fp4 = (k & 1) ? (packedByte >> 4) : (packedByte & 0x0f);
        const uint8_t scaleCode =
            scales[static_cast<size_t>(n) * groups + (k / 16)];
        acc += __half2float(input[static_cast<size_t>(m) * c.k + k]) *
               E2M1ToFloat(fp4) * Fp8E4M3ToFloat(scaleCode) * c.globalScale;
      }
      const float got =
          __half2float(outFull[static_cast<size_t>(m) * c.n + n]);
      num += static_cast<double>(got - acc) * (got - acc);
      den += static_cast<double>(acc) * acc;
    }
  }
  const float rel = den > 0.0 ? static_cast<float>(std::sqrt(num / den)) : 0.0f;
  const bool ok = rel <= relTol && canaryHits == 0;
  std::printf("  [%s] native m=%d k=%d n=%d%s%s relL2=%.3e canary=%d %s\n",
              c.name, c.m, c.k, c.n, c.n % 32 == 0 ? "" : " padded",
              outOfPlace ? " split" : "", rel, canaryHits, ok ? "OK" : "FAIL");
  release();
  return ok;
}

}  // namespace

int main(int argc, char** argv) {
  (void)argc;
  (void)argv;
  int dev = 0;
  if (cudaGetDevice(&dev) != cudaSuccess) {
    std::printf("SKIP: no CUDA device\n");
    return kSkip;
  }
  if (cudaDeviceGetAttribute(&GpuMajor, cudaDevAttrComputeCapabilityMajor, dev) !=
          cudaSuccess ||
      cudaDeviceGetAttribute(&GpuMinor, cudaDevAttrComputeCapabilityMinor, dev) !=
          cudaSuccess) {
    std::printf("SKIP: cannot query compute capability\n");
    return kSkip;
  }
  if (GpuMajor != 7 || GpuMinor != 0) {
    std::printf("SKIP: requires SM70 (got sm_%d%d)\n", GpuMajor, GpuMinor);
    return kSkip;
  }

  setenv("FASTLLM_SM70_NVFP4_QPN2", "0", 1);
  if (fastllm::sm70::Nvfp4QpnSupported()) {
    std::fprintf(stderr, "FAIL: Nvfp4QpnSupported should be false with "
                         "FASTLLM_SM70_NVFP4_QPN2=0\n");
    return kFail;
  }
  unsetenv("FASTLLM_SM70_NVFP4_QPN2");
  if (!fastllm::sm70::Nvfp4QpnSupported()) {
    std::printf("SKIP: QPN2 kernels not compiled for this device\n");
    return kSkip;
  }

  const Case cases[] = {
      {1, 256, 256, 1.0f, "m1"},
      {4, 256, 256, 1.0f, "m4"},
      {8, 128, 256, 1.0f, "m8"},
      {16, 256, 256, 1.0f, "m16"},
      {32, 256, 256, 1.0f, "m32"},
      {4, 256, 256, 0.25f, "m4_scale"},
      {4, 1536, 256, 1.0f, "m4_k1536"},
      {16, 512, 256, 1.0f, "m16_k512"},
  };

  bool allOk = true;
  for (const Case& c : cases) {
    allOk = RunCase(c, 3e-3f) && allOk;
  }

  const Case nativeCases[] = {
      {4, 256, 256, 1.0f, "native_m4"},
      {16, 256, 256, 1.0f, "native_m16"},
      {32, 256, 256, 1.0f, "native_m32"},
      {4, 1536, 256, 1.0f, "native_k1536"},
      {4, 256, 256, 0.25f, "native_m4_scale"},
      {16, 256, 256, 0.125f, "native_m16_scale"},
      // Logical N not a multiple of the 32-column tile. 5120x4120 is the
      // TP4-local GDN-in shape this padding exists for.
      {1, 5120, 4120, 1.0f, "native_pad_gdn"},
      {16, 512, 260, 1.0f, "native_pad_m16"},
      {4, 256, 300, 0.25f, "native_pad_m4_scale"},
  };
  for (const Case& c : nativeCases) {
    allOk = RunNativeCase(c, 3e-3f) && allOk;
  }

  // Same shapes again through the engine's allocation split: storage exactly
  // the native source, sidecar a separate Nvfp4QpnPackedBytes buffer.
  const Case splitCases[] = {
      {4, 256, 256, 1.0f, "split_m4"},
      {1, 5120, 4120, 1.0f, "split_pad_gdn"},
      {16, 512, 260, 0.125f, "split_pad_m16"},
  };
  for (const Case& c : splitCases) {
    allOk = RunNativeCase(c, 3e-3f, true) && allOk;
  }

  if (!allOk) {
    std::fprintf(stderr, "FAIL: one or more QPN2 cases diverged\n");
    return kFail;
  }
  std::printf("PASS: sm70 QPN2 NVFP4 regression\n");
  return kPass;
}
